add_custom_target(mcuboot_shared_property_target)
set_property(TARGET mcuboot_shared_property_target  PROPERTY KERNEL_HEX_NAME;zephyr.hex)
set_property(TARGET mcuboot_shared_property_target  PROPERTY ZEPHYR_BINARY_DIR;D:/nordicsemi/rareBit-Flags-Receivers/Receiver_PRO/build_1/mcuboot/zephyr)
set_property(TARGET mcuboot_shared_property_target  PROPERTY KERNEL_ELF_NAME;zephyr.elf)
set_property(TARGET mcuboot_shared_property_target  PROPERTY BUILD_BYPRODUCTS;D:/nordicsemi/rareBit-Flags-Receivers/Receiver_PRO/build_1/mcuboot/zephyr/zephyr.hex;D:/nordicsemi/rareBit-Flags-Receivers/Receiver_PRO/build_1/mcuboot/zephyr/zephyr.elf)
set_property(TARGET mcuboot_shared_property_target  PROPERTY SIGNATURE_KEY_FILE;root-ec-p256.pem)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;D:/ncs/v2.3.0/bootloader/mcuboot/boot/zephyr/pm.yml)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_FILES;D:/nordicsemi/rareBit-Flags-Receivers/Receiver_PRO/build_1/mcuboot/zephyr/include/generated/pm.yml)
